language: java
install: true
sudo: true
addons:
  apt:
    update: true
jdk:
  - openjdk11

stages:

  - name: build

  - name: publish_gh
    if: branch = master AND type IN (push)

jobs:
  include:

    - stage: build
      script: "./gradlew --stacktrace build"

    - stage: publish_gh
      script: "./gradlew --console=plain clean preparePages && ./gradlew gitPublishPush --stacktrace"
#   - "../../gradlew bintrayUpload --stacktrace"

