version: 2.1

orbs:
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: node test
          command: node --version
      - run:
          name: npm test
          command: npm --version
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube -Dsonar.login=${SONAR_TOKEN}
