# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
     - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
       # Runs a set of commands using the runners shell
    - name: Build documentation
      run: |
        ./gradlew asciidoctor
        mkdir ./current
        mkdir ./current/docs
        mv ./coderadar-test/build/docs ./current/docs
        
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./current/docs # The folder the action should deploy.
          COMMIT_MESSAGE: Update documentation [ci skip]
